# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuración explícita para PdfGeneratorService
    App\Service\PdfGeneratorService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Listener para auditar acciones en Doctrine (INSERT/UPDATE/DELETE)
    # Configuración 100% explícita para evitar errores de autowiring
    App\EventListener\DoctrineAuditSubscriber:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: postRemove, method: postRemove }


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
