nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000', 'https://*.ngrok-free.dev']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-USER-ID']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'https://*.ngrok-free.dev']
            allow_headers: ['Content-Type', 'Authorization', 'X-USER-ID']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
